### ISSUE TITLE
Top Cities table contains aggregated data instead of just the current month

### ISSUE THREAD

**Issue by pistvan** [StoneStepsInc/StoneStepsWebalizer#13]
After processing a whole year of access logs with GeoIP City database, I discovered that my site has more hits coming from some cities (e.g. Stockholm) than coming from the country of the city (Sweden).  
In my config file I set `DNSLookups no`, so my lookups are all based on GeoIP.

I think the city counters are not being reset when switching months, maybe `state_t::init_counters` method lacks a `ct_htab.reset()` call.

**Comment by StoneStepsInc** [comment]
I can reproduce it. Seems that ASN numbers are affected as well. Give me a couple of days to sort it out. This code has been through a few iterations as the state storage changed and it looks like I missed last couple of additions - cities and ASN stats.

**Comment by StoneStepsInc** [comment]
I just pushed fixes for the main branch and the 6.1.x branch (v6-1), but it looks like you are using the former. Have a look at whichever one you use - see if it works for you. These are the steps I used to verify. Note that page counts from country stats were also affected, so it's all city and ASN stats, plus country pages, in general, but just test what you need for your purposes. 

* Process a log file for one day in the middle of any month (e.g. 25th of October)
* Process a log file for one day in the middle of the next month (e.g. 25th of November)
* Make a copy of generated reports for the 2nd month and discard reports for the 1st month
* Delete all files from the output directory
* Process a log file for the same day of the 2nd month
* Compare reports for the 2nd month generated in both runs

Aside from different report dates, most reports must be the same (except for the index report and history), but because of this bug, all city/ASN counters will be much higher in the 1st case. Similarly, country page counts will be higher in the 1st case as well, even though other country counts will be correct.

Let me know if it works for you. Thanks.

**Comment by pistvan** [comment]
I tested it according to your steps and it looks okay.

**Comment by StoneStepsInc** [comment]
@pistvan Thanks for reporting it.
